### ISSUE TITLE
玩转 Kafka

### ISSUE THREAD

**Issue by bingooyong** [lvyong1985/note#28]
## Quick Run Kafka In Docker 
* 172.20.10.5 是HOST IP
* KAFKA_ADVERTISED_HOST_NAME 需要配置本机HOST IP否则容器网络外无法访问 kafka

` docker-compose.yml `
```yml
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.20.10.5
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

启动命令
```bash
docker-compose up -d
```

```bash

# 查看topic列表
docker exec -it kafka-docker_kafka_1 /opt/kafka/bin/kafka-topics.sh --list --zookeeper 172.20.10.5:2181
# 创建topic
docker exec -it kafka-docker_kafka_1 /opt/kafka/bin/kafka-topics.sh --create --topic test-topic --zookeeper 172.20.10.5:2181 --partitions 1 --replication-factor 1
#  测试容器外发送消息
docker exec -it kafka-docker_kafka_1 /opt/kafka/bin/kafka-producer-perf-test.sh --topic test-topic --num-records 1000 --record-size 100 --producer-props  bootstrap.servers=172.20.10.5:9092 --throughput -1

```

感谢：
[Github](https://github.com/wurstmeister/kafka-docker)
[DockerHub](https://hub.docker.com/r/wurstmeister/kafka)
[kafka的Docker镜像使用说明(wurstmeister/kafka)](https://blog.csdn.net/boling_cavalry/article/details/85395080)
